### ISSUE TITLE
missing program file

### ISSUE THREAD

**Issue by arumoybera** [leonvandenbeukel/7-Segment-Digital-Clock#1]
need the arduino program file urgently.

**Comment by leonvandenbeukel** [comment]
Hi arumoybera, I've just uploaded the code to my GitHub page. Goodluck with
it and send me some pictures of your own clock :-)

Regards,
Leon van den Beukel

2018-02-12 16:50 GMT+01:00 arumoybera <notifications@github.com>:

**Comment by leonvandenbeukel** [comment]
Uploaded the code.

**Comment by Dipak-Kumar-Biswas** [comment]
I found an error in compiling 
"3D-7-Segment-Digital-Clock:100:6: error: 'class Timer' has no member named 'every'
   t3.every(50, updateHue);"
How can I solve it?

**Comment by leonvandenbeukel** [comment]
You need to install the correct timer library and then it should work.

Regards,
Leon

**Comment by Dipak-Kumar-Biswas** [comment]
will you be kind enough to give the link of the correct library?
Thanx........

**Comment by Dipak-Kumar-Biswas** [comment]
I tried different ways to Solve the " "3D-7-Segment-Digital-Clock💯6: error: 'class Timer' has no member named 'every'
t3.every(50, updateHue);" problem but failed. Requested to mail or give the link for correct timer library.
Thank you in advance..

**Comment by leonvandenbeukel** [comment]
You need to install this library: https://github.com/JChristensen/Timer
