### ISSUE TITLE
I have only 1 issue with the compilation of the code.

### ISSUE THREAD

**Issue by wilbertowski** [leonvandenbeukel/7-Segment-Digital-Clock#5]
When I compile,it tells me this:parse error in template argument list
It uses pink to highlight this line: FastLEDs.addleds<WS2812B,DATA_in.
Please sir I need help,but I just put my Arduino uno r3 board alone is it supposed to compile? I really appreciate your work.reply me on wilbertuwadia@gmail.com.   thanks

**Comment by leonvandenbeukel** [comment]
Hi Wilbert, I think you missed a comma or parameter. The line should look something like this:
FastLED.addLeds<WS2812B, DATA_PIN, GRB>(LEDs, NUM_LEDS);

**Comment by wilbertowski** [comment]
Thanks sir,I appreciate your Swift response, I will check it and get back
to you sir.thanks
