### ISSUE TITLE
Thank you sir, I made it,the error is gone

### ISSUE THREAD

**Issue by wilbertowski** [leonvandenbeukel/7-Segment-Digital-Clock#6]
I downloaded the zip files and uploaded it to my Arduino app and it worked,thanks sir.I love you sir

**Comment by leonvandenbeukel** [comment]
Great!

**Comment by PeterSteinwarz** [comment]
Hallo Leon!

I need support! I build the clock and load the Software – the clock works (  the points between Min & Hours are still in light, but not blinking ! ) !!! In the second phase I would like to implent the Bluetooth Funktion and the Temp. & Humidity Funktion. I had connect this modules with the board and load the App but nothing happens!!!

What shall I do – I see, as the library SoftwareSerial.h is not includet in your Sketch – DigitalClockV2.ino.

 

Please excuse my bad english – I think for you better  for you as my German.

 

Best greetings

Peter

psteinwarz@gmx.de

 

Peter Steinwarz

Hagenring 9

38476 Barwedel

+495366-5612

+49 171 9830272
