### ISSUE TITLE
Power Supply

### ISSUE THREAD

**Issue by osowers** [leonvandenbeukel/7-Segment-Digital-Clock#8]
Hello- we are two middle school kids trying to build a clock similar to yours. We have the materials you provided links for and we were wiring the breadboard and we ran into a problem. The Problem was we didn't know which power supply to buy. Can you please Respond to this with a link to the one you used and anything else you feel would be useful? Thank you!

**Comment by leonvandenbeukel** [comment]
Hi, you need a 5 volt power supply with a minimum of 5 ampere. Good luck with your project 😃
